eureka:
  client:
    service-url:
      defaultZone: http://192.168.9.147:8000/eureka/
spring:
  #### MYSQL连接信息
  datasource:
    url: jdbc:mysql://192.168.9.130:3306/trade?userUnicode=true&&characterEncoding=utf8&allowMultiQueries=true
    username: trade-read
    password: sigo@123
    driver-class-name: com.mysql.cj.jdbc.Driver
    ### 数据源类别
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 连接池的配置信息
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,log4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
      # 配置DruidStatFilter
      web-stat-filter:
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      # 配置DruidStatViewServlet
      stat-view-servlet:
        url-pattern: "/druid/*"
        # IP白名单(没有配置或者为空，则允许所有访问)
        allow:
        # IP黑名单 (存在共同时，deny优先于allow)
        deny:
        #  禁用HTML页面上的“Reset All”功能
        reset-enable: false
        # 登录名
        login-username: admin
        # 登录密码
        login-password: 123456

#elasticsearch
  es:
    ip: 192.168.9.206
    port: 9300
    cluster:
      name: elasticsearch


#多数据源配置
mysql:
  datasource:
#      商户
    merchant:
      url: jdbc:mysql://192.168.9.152:3306/merchant?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
      username: merchant-read
      password: sigo@123
      driver-class-name: com.mysql.cj.jdbc.Driver
#    订单
    orders:
      url: jdbc:mysql://192.168.9.130:3306/trade?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
      username: trade-read
      password: sigo@123
      driver-class-name: com.mysql.cj.jdbc.Driver
#      购物车
    spartan:
      url: jdbc:mysql://10.0.180.165:3306/spartan?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
      username: b2badmin
      password: Abcd@1234
      driver-class-name: com.mysql.cj.jdbc.Driver

appCode: b2b
sms:
  sign: '眼镜圈'
  sender: xuanwu

url:
  erpapi: http://erpapi.vsigo.cn/
  soldOutProduct: https://t.yjq.com/platform/product/sold-out-products